<?php

namespace AppBundle\Repository;

/**
 * TypeAppointmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAppointmentRepository extends \Doctrine\ORM\EntityRepository
{
}
