messagerie_homepage:
    path:     /
    defaults: { _controller: MessagerieBundle:Default:message }

messagerie_new_messages:
    path: /new
    defaults: { _controller: MessagerieBundle:Default:new }