AppBundle\Entity\Appointment:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\AppointmentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        day:
            type: datetime
        hour:
            type: time
        isValidated:
            type: boolean
    lifecycleCallbacks: {  }
