AppBundle\Entity\TypeAppointment:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\TypeAppointmentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        label:
            type: string
            length: 255
    lifecycleCallbacks: {  }
